name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 22
  +       cache: npm
  +       cache-dependency-path: package-lock.json
     

      - name: install dependencies
        run: npm install

      - name: run webview build
        run: npm run build --workspace webview

      - name: run compile
        run: npm run compile
